language: python
python: 3.6
install:
- pip install coveralls nose
- pip install .
script:
- nosetests --with-coverage --cover-package=usb_manager
after_success:
- coveralls
deploy:
  provider: pypi
  user: M-Gregoire
  password:
    secure: TyE2Tp4A7gDfQcdqiA3jf46RkUpi6SIRUnZsXZjH9Otu5DAHqQ9xhhFQKZrPWEJw3dUxE6T17EvFR25fEf484yLq/PJieLcb2+z1lUElRp/gkfdBZ4+FQv860h+YxHO11ZwFfL3kEdPur9zQoiTp+Uy6n0IBOnD882FqCFY87FxMT8AfUoaRSz3E0QhJvXyuaqId1M2Sd98gksnO+MtG5RJ/wj7bQVKzEbx25aLR8Z0rR7vsfw5DZIbce/NSVnagYHluvFQ2A09hwdxsxpaUyYmAeALvb6jMPln1ixqpriCyD/Uu9cKngoKcmoDSjoZxnIog0dEpUnaqLj3F+Li4Gklt7yFsiVs/B+H72vITwbwXR1IMC9MzG+z/XFN2jSE0wwFGE1E+YfDV1+kx/Rnsgf+FbldzSCx47FIpes43LwElUcPNL3uBkIZTdeOGCumYiYEl5ogWED4VNK7ahf5k8Hv+seeRDgSp1PB5TDW30thp4EQow6gyMZRfiU0aCVSVtiMbfbTa7O9uNzlA38YazxFzyEEZoOYjTfcgfdRh0a7qXLex6nuu5mY5RGVSD30sG1UQSh+t7dYYFrBgxoQ2pfKSfa2BbE+/KlgtTvh16OIa9kxw2a4GHug3kJjWt46g8jlugElt1C4R/5OmSgTMbZGt26WLOAsfHrpPDLs5RpU=
